version: '3.8'
services: 
  indy-sdk:
    build: .
    image: jrayback/indy-sdk:latest
    container_name: indy-sdk
    stdin_open: true
    tty: true
    # need to mount the wallet at the root of the home dir
    # need for docker to create a volume for node_modules
    #  so that whatever gets installed by npm is persisted locally
    # the rest of the app directory I want to map into the container
    #  these are all my source files
    volumes:
      - /Users/jrayback/src/personal/misc/indy/jmr-indy-sdk/.indy_client:/root/.indy_client
      - /Users/jrayback/src/personal/misc/indy/jmr-indy-sdk/.ssh:/root/.ssh
      - /root/app/node_modules
      - .:/root/app
    command: /bin/bash